version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REPOSITORY_NAME: "enterprise-mlops-app"

phases:
  install:
    # Removed runtime-versions section
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR Public..."
      - aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047719639376.dkr.ecr.us-east-1.amazonaws.com
      - echo "Setting repository variables..."
      - REPOSITORY_URI=047719639376.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
      - export IMAGE_TAG="latest"
      - echo "Downloading model from S3..."
      - mkdir -p model
      - aws s3 cp $MODEL_S3_PATH ./model/iris_model.joblib

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "Running tests inside Docker container..."
      - docker run --rm $REPOSITORY_URI:$IMAGE_TAG pytest tests/

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Preparing artifact metadata..."
      - printf '[{"name":"ImageUri","value":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imageDetail.json

artifacts:
  files:
    - '**/*'
  discard-paths: no
